### ISSUE TITLE
need example to connect to ttn network

### ISSUE THREAD

**Issue by lucky2004alex** [HelTecAutomation/ASR650x-Arduino#144]

**Comment by ScholliYT** [comment]
There is documentation about this. Please have a look here: https://heltec-automation-docs.readthedocs.io/en/latest/cubecell/lorawan/connect_to_gateway.html#connect-to-ttn

Otherwise, have a look on Youtube or get started via the examples provided with the CubeCell boards. The Example under LoRa>LoRaWan>LoRaWan is a good starting point.
