### ISSUE TITLE
micros() function missing in Arduino.h

### ISSUE THREAD

**Issue by oscaropenness** [HelTecAutomation/ASR650x-Arduino#54]
For using ultrasonic sensors, accurate (microsecond) time measurements are necessary.
The `micros()` function seems currently not implemented in the board definition for the ArduinoIDE.
Using the implemented `millis()` function is unfortunately not precise enough.

Can the `micros()` function be implemented in `Arduino.h` as well?

**Comment by heyderpaez** [comment]
I have the same issue. I have not even been able to execute the basic examples for HTCC-AB01 due to the error of the micros () function.

**Comment by lnlp** [comment]
This appears to be a bug and really should be fixed for compatibility with the basics of the Arduino framework.

**Comment by OstertagM** [comment]
I have same problem

**Comment by kkalbaugh** [comment]
Also having the same issue with Lorawan example and using a dallas DS18B20.

**Comment by Heltec-Aaron-Lee** [comment]
Just added two examples: [micros](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/libraries/Basics/examples/micros/micros.ino) and [millis](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/libraries/Basics/examples/millis/millis.ino).

**micros**
The micros function uses the internal system ticker (48MHz timer), this timer of ASR6501 is not accurate, as tested, it has 1.7% error.
![image](https://user-images.githubusercontent.com/32860565/76745171-5e2af500-67b0-11ea-864f-cc860d435b95.png)

The delay in the example is 1000ms, ideally, the output value here should be 1000000.

But look at the printed time stamp, each print have 20 - 22ms error. It means the actual `delay(1000); ` spend 1020 - 1022ms. Because the delay uses internal system ticker too.

So the error is `(1020000 - 1002735) / 1020000 ≈ 1.7%`

That’s why I didn’t use system ticker for LoRaWAN operations. Another problem is the system ticker can’t run during the deep sleep period, wake up from deep sleep will make the micros back to 0.

**millis**
![image](https://user-images.githubusercontent.com/32860565/76745197-6b47e400-67b0-11ea-94cd-69da1bf3179e.png)

The millis function uses external 32.768KHz RTC clock, it a very accurate timer, and can run during the deep sleep period. As the picture has shown, it’s the same with the delay time.

But the minimum period is `1/32768 ≈ 30us`, can’t be the source of micros.

**Comment by Heltec-Aaron-Lee** [comment]
This problem also talk here:
[http://community.heltec.cn/t/cubecell-micros-function/985/3](http://community.heltec.cn/t/cubecell-micros-function/985/3)
